services:
  reservations:
    container_name: reservations
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    depends_on:
      - mongo
    ports:
      - "7000:7000"
    volumes:
      - .:/usr/src/app

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongo
    ports:
      - "7001:7001"
    volumes:
      - .:/usr/src/app

  payments:
    container_name: payments
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: always
