services:
  reservations:
    container_name: reservations
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    depends_on:
      - mongo
    env_file:
      - ./apps/reservations/.env
    ports:
      - "7000:7000"
    volumes:
      - .:/usr/src/apps

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    depends_on:
      - mongo
    env_file:
      - ./apps/auth/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/apps

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: always
